# Custom Language File for Launcher Customizer

[ejs.app]
title = "Ordina Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/JoeyScheidt/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/JoeyScheidt/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE DANS LES TERRES D'AURORE"
welcomeDescription = "Le Royaume d'Ordina renaît de ses cendres après l'Éclipse Ordienne qui l'a dévasté. La reconstruction est en marche, poussée par de nombreux personnages hauts en couleur..."
welcomeDescCTA = "Quel chemin allez vous suivre ? Découvrez le en parcourant le Royaume d'Ordina."
